### ISSUE TITLE
Files src blob should only match *.es.js by default

### ISSUE THREAD

**Issue by jbalsas** [kenjiheigel/liferay-karma-config#1]
Hey @kenjiheigel, for Liferay Portal, https://github.com/kenjiheigel/liferay-karma-config/blob/master/index.js#L39 should just match `src/**/*.es.js`. This is the convention to differentiate ES2015 modules which are the only ones we'll be testing for now.

**Comment by kenjiheigel** [comment]
@jbalsas, updated: https://github.com/kenjiheigel/liferay-karma-config/commit/dd9f790801622f1a84079ab470145620447f88cf

Does this need to be applied right now to Liferay Portal modules in the existing npm dependencies? Or is it ok to leave it for now, and update later?

**Comment by jbalsas** [comment]
Thanks @kenjiheigel!

It's fine, I'll take care of that whenever I go over some of those modules next time ☺️
